version: '3.1'

services:
    consul:
        image: consul:1.4.2
        command: consul agent -dev -ui -client 0.0.0.0
        ports:
            - 8300:8300
            - 8500:8500
            - 8600:8600
    consul-config-loader:
        image: jhipster/consul-config-loader:v0.3.0
        volumes:
            - ./consulConfig.local:/config
        environment:
            - INIT_SLEEP_SECONDS=5
            - CONSUL_URL=consul
            - CONSUL_PORT=8500
