spring:
    jpa:
        show_sql: true
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
    mvc:
        favicon:
            enabled: false
    main:
        banner-mode: "off"
        allow-bean-definition-overriding: true
    profiles:
        active: local
server:
    servlet:
        session:
            cookie:
                http-only: true
    max-http-header-size: 32000
logging:
    level:
        root: info
        online.oboz: info
