spring:
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
    mvc:
        favicon:
            enabled: false
    main:
        banner-mode: "off"
        allow-bean-definition-overriding: true
server:
    servlet:
        session:
            cookie:
                http-only: true
logging:
    level:
        root: INFO
        online.oboz: INFO
