spring:
    security.oauth2.resourceserver.jwt.jwk-set-uri: http://keycloak:8080/auth/realms/master/protocol/openid-connect/certs
    profiles:
        active: preprod
    mail:
        host: mailhog.services
        port: 1025
        username: 'notreply@bu1.loc'
        password: ''
        properties:
            mail:
                smtp:
                    starttls:
                        enable: false
                        required: false
                    auth: false
                    connectiontimeout: 10000
                    timeout: 15000
                    writetimeout: 15000
                debug: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://pg-01-01.preprod.oboz:5432/elp
        username: PG_USER
        password: PG_PASSWORD
        auto-commit: false
        poolName: main-pool
        hikari:
            poolName: main-pool
            auto-commit: false

sms-sender:
    url: 'http://sms-sender.r14.k.preprod.oboz:30080'

cron:
    expression: 0 /5 * * * *

#    При изменении minCountTrip нужно также поменять minDateTrip наа текущее значение
auto-advance:
    min-date-trip: "2020-01-01T00:00:00+00:00"
    min-count-trip: 3
    required-download-docs: true

notification:
    sms-enable: false
    email-enable: true

services:
    bstore-url: https://preprod.oboz.online/api/bstore
    orders-api-url: https://preprod.oboz.online/api/orders/dispatcher/orders
    report-server-url: https://reports.oboz.com/reportserver/reportserver/httpauthexport?key=avance_request&user=bertathar&apikey=nzybc16h&p_trip_num=
    keycloak:
        url: http://keycloak.r14.k.preprod.oboz:30080/authhttp://keycloak.r14.k.dev.oboz:30080/auth/realms/master/protocol/openid-connect
        auth:
            username: ADVANCE_USER
            password: ADVANCE_PASSWORD
