spring:
    security.oauth2.resourceserver.jwt.jwk-set-uri: http://keycloak.r14.k.preprod.oboz:30080/auth/realms/master/protocol/openid-connect/certs
    profiles:
        active: preprod
    mail:
        host: mailhog.services
        port: 1025
        username: 'notreply@bu1.loc'
        password: ''
        properties:
            mail:
                smtp:
                    starttls:
                        enable: false
                        required: false
                    auth: false
                    connectiontimeout: 10000
                    timeout: 15000
                    writetimeout: 15000
                debug: false

    cloud:
        stream:
            binders:
                events_host:
                    default: true
                    type: rabbit
            rabbit:
                bindings:
                    orders-update:
                        producer:
                            bindingRoutingKey: event.advance.create
                            routingKeyExpression: '"event.advance.create"'
            bindings:
                orders-update:
                    destination: events
                    binder: events_host
                    group: b2b.orders.update

    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://pg-01-01.preprod.oboz:5432/elp
        username: PG_USER
        password: PG_PASSWORD
        auto-commit: false
        poolName: main-pool
        hikari:
            poolName: main-pool
            auto-commit: false

    rabbitmq:
        host: rabbitmq.services
        port: 5672
        username: RMQ_USER
        password: RMQ_PASSWORD
        virtual-host: events

sms-sender:
    url: 'http://sms-sender.r14.k.preprod.oboz:30080'

cron:
    creation: 0 0/30 * * * *
    update: 0 0/30 * * * *

#    При изменении minCountTrip нужно также поменять minDateTrip наа текущее значение
auto-advance:
    min-date-trip: "2020-01-01T00:00:00+00:00"
    min-count-trip: 3
    required-download-docs: true

notification:
    #    msec
    delay.sms-send: 600000
    sms-enable: false
    email-enable: true
    lk-url: https://preprod.oboz.online/carrier-advance/

services:
    bstore-url: https://preprod.oboz.online/api/bstore/
    orders-api-url: https://preprod.oboz.online/api/orders/dispatcher/orders/%d/trips/%d/documents
    report-server-url: http://reports.oboz.com/reportserver/reportserver/httpauthexport?key=avance_request&user=bertathar&apikey=nzybc16h&p_trip_num=
    keycloak:
        url: https://preprod.oboz.online/auth/realms/master/protocol/openid-connect
        auth:
            username: ADVANCE_USER
            password: ADVANCE_PASSWORD
