spring:
    security.oauth2.resourceserver.jwt.jwk-set-uri: http://keycloak:8080/auth/realms/master/protocol/openid-connect/certs
    profiles:
        active: preprod
    mail:
        host: mailhog.services
        port: 1025
        username: 'notreply@bu1.loc'
        password: ''
        properties:
            mail:
                smtp:
                    starttls:
                        enable: false
                        required: false
                    auth: false
                    connectiontimeout: 10000
                    timeout: 15000
                    writetimeout: 15000
                debug: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://pg-01-01.preprod.oboz:5432/elp
        username: PG_USER
        password: PG_PASSWORD
        auto-commit: false
        poolName: main-pool
        hikari:
            poolName: main-pool
            auto-commit: false

application:
    limits:
        min-trip-count: 5
        required-download-docs: true

sms-sender:
    url: 'http://sms-sender.r14.k.preprod.oboz:30080'

cron:
    expression: 0 /5 * * * *

#    При изменении minCountTrip нужно также поменять minDateTrip наа текущее значение
auto-advance:
    min-date-trip: 2017-07-03T21:44:49
    min-count-trip: 3

notification:
    sms-enable: true
    email-enable: true
