spring:
    security.oauth2.resourceserver.jwt.jwk-set-uri: http://keycloak:8080/auth/realms/master/protocol/openid-connect/certs
    profiles:
        active: prod
    mail:
        host: mail.oboz.com
        port: 587
        username: notreply@bu1.loc
        password: 1qazxsw2
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true
                        required: true
                    auth: true
                    connectiontimeout: 10000
                    timeout: 15000
                    writetimeout: 15000
                debug: false

    cloud:
        stream:
            binders:
                events_host:
                    default: true
                    type: rabbit
            rabbit:
                bindings:
                    orders-update:
                        producer:
                            bindingRoutingKey: event.orders.update
                            routingKeyExpression: '"event.orders.update"'
            bindings:
                orders-update:
                    destination: events
                    binder: events_host
                    group: b2b.orders.update

    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://pg-01-01.prod.oboz:5432/elp
        username: PG_USER
        password: PG_PASSWORD
        auto-commit: false
        poolName: main-pool
        hikari:
            poolName: main-pool
            auto-commit: false

    rabbitmq:
        host: rmq-01.prod.oboz
        port: 5672
        username: RMQ_USER
        password: RMQ_PASSWORD
        virtual-host: events

sms-sender:
    url: 'http://sms-sender.r14.k.preprod.oboz:30080'

cron:
    creation: 0 /60 * * * *
    update: 0 /60 * * * *

#    При изменении minCountTrip нужно также поменять minDateTrip наа текущее значение
auto-advance:
    min-date-trip: "2020-01-01T00:00:00+00:00"
    min-count-trip: 3
    required-download-docs: true

notification:
    #    msec
    delay.sms-send: 600000
    sms-enable: false
    email-enable: true
    lk-url: https://oboz.online/carrier-advance/

services:
    bstore-url: https://oboz.online/api/bstore/
    orders-api-url: https://oboz.online/api/orders/dispatcher/orders/%d/trips/%d/documents
    report-server-url: https://reports.oboz.com/reportserver/reportserver/httpauthexport?key=avance_request&user=bertathar&apikey=nzybc16h&p_trip_num=
    keycloak:
        url: http://keycloak:8080/auth/realms/master/protocol/openid-connect
        auth:
            username: ADVANCE_USER
            password: ADVANCE_PASSWORD
