spring:
    security.oauth2.resourceserver.jwt.jwk-set-uri: http://keycloak:8080/auth/realms/master/protocol/openid-connect/certs
    profiles:
        active: prod
    mail:
        host: mail.oboz.com
        port: 587
        username: notreply@bu1.loc
        password: 1qazxsw2
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true
                        required: true
                    auth: true
                    connectiontimeout: 10000
                    timeout: 15000
                    writetimeout: 15000
                debug: false

    cloud:
        stream:
            binders:
                events_host:
                    default: true
                    type: rabbit
            rabbit:
                bindings:
                    advance-create:
                        producer:
                            bindingRoutingKey: event.advance.create
                            routingKeyExpression: '"event.advance.create"'
            bindings:
                advance-create:
                    destination: events
                    binder: events_host
                    group: advance.create

    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://pg-01-01.prod.oboz:5432/elp
        username: PG_USER
        password: PG_PASSWORD
        auto-commit: false
        poolName: main-pool
        hikari:
            poolName: main-pool
            auto-commit: false

    rabbitmq:
        host: rmq-01.prod.oboz
        port: 5672
        username: RMQ_USER
        password: RMQ_PASSWORD
        virtual-host: events

# access-only-emails-list
accessed-users:
    ids:
    emails:
        ttrunina@oboz.com,
        tborisova@oboz.com,
        dpopov@oboz.com,
        vlaptev@oboz.com,
        skabanov@oboz.com,
        kabanovsergey777@gmail.com,
        ncheglova@oboz.com,
        vhrol@oboz.com,
        okostina@oboz.com,
        vnikitenko@oboz.com

services:
    # tokenAuthUrl in RestService?
    keycloak:
        url: https://preprod.oboz.online/auth/realms/master/protocol/openid-connect
        token-postfix: '/token'
        token-body: 'grant_type=password&client_id=elp&username=%s&password=%s'
        auth:
            username: oboztech_payment@oboz.tech
            password: 1870

    # BStore-URL for BStore-service
    bstore:
        url: https://oboz.online/api/bstore/
        pdf: 'pdf/'

    #Trip-advance service for check advance-state of trip and give advance.
    trip-advance-service:
        trip-null-cost-error: "Укажите стоимость заказа поставщика."
        trip-cost-error: "Стоимость заказа поставщика должна быть %s %s руб."
        trip-cost-gt: "больше, чем"
        trip-cost-lt: "меньше, чем"
        trip-contracts-error: "Внесите контакты в раздел «Авансирование» в карточке контрагента."
        trip-docs-error: "Загрузите 'Договор-заявку' или 'Заявку' в разделе «Документы»."

    reports:
        url: https://reports.oboz.com/reportserver/reportserver/httpauthexport?
        type-key: key=avance_request&
        user: user=bertathar&
        api-key: apikey=nzybc16h&
        format: format=PDF
        template-params: p_trip_num=%s&p_avance_sum=%s&p_avance_comission=%s&


    #Autoadvance-service
    auto-advance-service:
        min-paid-advance-count: 3
        # TODO: search by e-mail, not id
        # ID of auto-advance-author-person - 'oboztech_payment@oboz.tech'
        auto-author: 62911
        # Interval for operations with 'new advance' in minutes
        # Use for: search 'new assigned' trips and search 'unread' advances
        newadvance-inteval: 60
        # Auto-created advance comment
        comment: "Auto created"
        # Auto-advance checker-crons?
        cron:
            # Create auto-advances for auto-contractors trips
            create: 0 0/30 * * * *
            # Update: 1) auto-contractors; 2) file's uuid?
            update: 0 0/30 * * * *
            # Scheduled-notifications (delayed sms)
            notify: 0 0/30 * * * *

    #Notification-service
    notifications:
        #create message lk-url
        lk-url: https://oboz.online/carrier-advance/

        #link-shortener url
        cut-link-url: https://clck.ru/--?url=

        # SMS-config
        sms:
            # "Simple" (at-moment) SMS-notify unable
            enable: false
            # Only scheduled SMS-notify enable
            schedule-enable: true
            # Cut LK-links for short-SMS enable
            cut-links: true
            # Sms-sender url
            sender-url: http://sms-sender.r14.k.preprod.oboz:30080/v1/send-sms
            # SMS-templates
            sms-phone-template: 7%s
            sms-message-template:
                "Компания ОБОЗ предлагает аванс по заказу %s на сумму %.0f руб., для просмотра пройдите по ссылке \n %s"
            sms-default-number: 8080

        # Email-config
        email:  #  sender config in spring.mail
            # At-moment simple email-notify enable.
            email-enable: true
            # "Delayed" emails is unable now, emails not scheduled.
            email-schedule-enable: false
            # Cut-links unable in e-mail now, emails has long-link.
            cut-links: false
            # E-mail templates
            email-header-template:
                "Компания «ОБОЗ» предлагает аванс по заказу %s"
            email-message-template:
                "Компания «ОБОЗ» предлагает аванс по заказу %s на сумму %.0f руб., \n для просмотра пройдите по ссылке \n%s"
